- name: Create a resource group
  azure_rm_resourcegroup:
    name: healthplan_resource_group
    location: eastus

- name: Create storage account
  azure_rm_storageaccount:
    resource_group: healthplan_resource_group
    name: healthplanaccount
    account_type: Standard_LRS

- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: healthplan_resource_group
    name: healthplan_virtual_network
    address_prefixes: "10.10.0.0/16"

- name: Subnet1
  azure_rm_subnet:
    resource_group: healthplan_resource_group
    name: subnet1
    address_prefix: "10.10.0.0/24"
    virtual_network: healthplan_virtual_network

- name: Create a public ip
  azure_rm_publicipaddress:
    resource_group: healthplan_resource_group
    allocation_method: Static
    name: publicip1

- name: Create security group that allows SSH
  azure_rm_securitygroup:
    resource_group: healthplan_resource_group
    name: secgroup001
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 101
        direction: Inbound

- name: Create NIC
  azure_rm_networkinterface:
    resource_group: healthplan_resource_group
    name: nic001
    virtual_network: healthplan_virtual_network
    subnet: subnet1
    public_ip_name: publicip1
    security_group: secgroup001

- name: Create a virtual machine
  azure_rm_virtualmachine:
   resource_group: healthplan_resource_group
   name: healthplanvm01
   vm_size: Standard_B1ls
   admin_username: floyed
   ssh_password_enabled: false
   ssh_public_keys: 
    - path: "{{ variables.msg.path }}"
      # key_data: "{{ ssh_public_key }}"
      key_data: "{{ lookup('file', variables.msg.ssh_public_key_path ) }}"
   image:
    offer: Centos
    publisher: OpenLogic
    sku: '7.1'
    version: latest